export const CONFIG_OPTION = 'CONFIG_OPTION';
export const PERFECT_ORDER = 'PERFECT_ORDER';
export const GET_ORDER_LIST = 'GET_ORDER_LIST';
export const GET_MORE_ORDER = 'GET_MORE_ORDER';
export const GET_ORDER_DETAIL = 'GET_ORDER_DETAIL';
export const GET_COMPANY_ACHIEVEMENT = 'GET_COMPANY_ACHIEVEMENT';
export const GET_COMPANY_MONTHLY_ACHIEVEMENT = 'GET_COMPANY_MONTHLY_ACHIEVEMENT';