export const GET_PERSON_ACHIEVEMENT = 'GET_PERSON_ACHIEVEMENT';
export const GET_PERSON_MONTHLY_ACHIEVEMENT = 'GET_PERSON_MONTHLY_ACHIEVEMENT';
export const GET_COMPANY_ACHIEVEMENT = 'GET_COMPANY_ACHIEVEMENT';
export const GET_COMPANY_MONTHLY_ACHIEVEMENT = 'GET_COMPANY_MONTHLY_ACHIEVEMENT';
export const GET_STORE_ACHIEVEMENT = 'GET_STORE_ACHIEVEMENT';
export const GET_STORE_MONTHLY_ACHIEVEMENT = 'GET_STORE_MONTHLY_ACHIEVEMENT';